### ISSUE TITLE
Allow SDMX sub-series to be shown

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#109]
Some SDMX files have sub series. For example,  for 1.a.2 (Proportion of total government spending on essential services (education, health and social protection)), Kyrgyzstan have 3 series in their SDMX file:
- Proportion of total government spending on education
- Proportion of total government spending on health
- Proportion of total government spending on social protection

As all of the disaggregations and unit measures are the same for all three series, the graph will only show one of the series as all of the data is being recognised as the series.

To fix this, I think that we should have a separate toggle option called Series type, where the site will recognise that there are more that one series and then the toggle option could be the series descriptions (for this example, the descriptions are above).

I also think this would be good solution for non-SDMX files as I know in UK we use Units column for separate series also.

@brockfanning @AnnCorp @SavvasStephanides what are your thoughts?

**Comment by brockfanning** [comment]
Would this be another special column, like 'Year', 'Value', and 'Units'? So another column called 'Series' which generates "radio buttons" just like Units, but which is separate from Units?

Maybe that's too low-level of a question at this point. Maybe a mock-up would be a good next step?

Lastly just a related thought: I have definitely noticed the fact that in the SDMX world, the "series" is usually the main entity, whereas in Open SDG we have opted to make the "indicator" the main entity.

**Comment by LucyGwilliamAdmin** [comment]
Yes, I think it would be another special column.

Maybe the indicator page with just a Series toggle would look like:
![series-toggle](https://user-images.githubusercontent.com/43404358/75776090-361caa00-5d4b-11ea-8c01-9ea06118e373.png)

And the indicator page with a Series and Units toggle would look like:
![series-units-toggle](https://user-images.githubusercontent.com/43404358/75778971-b1348f00-5d50-11ea-9fea-8fb4b745175b.png)


In those images, I actually put Units and Series above the sub-category section as as I was making it, I thought that might make more sense. @brockfanning @AnnCorp what are your thoughts?

**Comment by brockfanning** [comment]
This was merged into Open SDG.
