### ISSUE TITLE
Automate the indicator_sort_order field

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-build#11]
There's a metadata field called "indicator_sort_order" which is required for Open SDG. But it's not something that really needs to be changed ever. Is there any way that sdg-build to add that field automatically during the build, so that the data providers would not have to worry about it?

**Comment by dougmet** [comment]
I feel like I remember a lot of discussion about this, which was why it stayed manual. However, I’d be more then willing to work something up that could be manually overridden.

**Comment by brockfanning** [comment]
I see, like if a country wanted to manually position some indicators at the end of the list, for whatever reason.

My image of this was something where, if the indicator does not already have a value in indicator_sort_order, then sdg-build adds it automatically before building the json. So countries could still control it in the current way, but wouldn't be required to, if they are fine with a standard sort order.

**Comment by brockfanning** [comment]
I believe that what I described above is in place, and the indicator_sort_order is not technically required anymore. I'll test this to be sure, before closing.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Kyrgyzstan aren't using indicator_sort_order at all and their indicators are in correct order so think this is done?

**Comment by brockfanning** [comment]
Ok cool, closing now.
