### ISSUE TITLE
Write to SDMX

### ISSUE THREAD

**Issue by dougmet** [open-sdg/sdg-build#15]
Write out data and metadata to SDMX format.

This will require more information from users. Most notably a DSD (Data Structure Definition) which maps column names and dissagregation categories to UN standards on an indicator by indicator basis.

cf. ONSdigital/sdg-indicators#2891

Start here for specifications https://sdmx.org/?page_id=5008

**Comment by brockfanning** [comment]
Closing this as a duplicate of #52
