### ISSUE TITLE
Add a jsonschema schema for metadata

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-build#169]
Internally we are using jsonschema to validate metadata, but we don't allow for a jsonschema to be used directly. We only have the OpenSDGSchema which is basically the Prose.io schema. Let's add a simple class to allow using jsonschema directly.

**Comment by jwestw** [comment]
I feel these json schemas will be very much related to my work with CSVW. Would like to chat about what's being generated and used here.

**Comment by brockfanning** [comment]
@jwestw The issue was named vaguely, but I just renamed it to clarify that it's about metadata. Right now, we rely on a schema to validate indicator metadata, but we only support one format for that schema, which is this [Prose.io schema format](https://github.com/open-sdg/open-sdg-data-starter/blob/develop/_prose.yml). This choice was made because we were recommending Prose.io for editing indicators, so we already needed that file to be in the data repository - so it made sense to use it for indicator metadata validation as well. But for implementations that do not use Prose.io, it doesn't make much sense to require a Prose-specific schema format.

When it comes to CSVW then we're talking about about a *data* schema, which is a different concern. It's definitely something that we need to resolve soon, both for CSVW support, and for tickets like https://github.com/open-sdg/open-sdg/issues/814. We should start discussion of a data schema here in another issue, for sure.
