### ISSUE TITLE
Output SDG data in GeoJSON format

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-build#18]
Moving this issue over from https://github.com/open-sdg/open-sdg/issues/74

This will depend on something like #16 but we can discuss in the meantime.

**Comment by brockfanning** [comment]
There is not yet a final standard for how the SDG data (such as, all the years, and any disaggregation) will be put into GeoJSON format. Presumably it will be in the "properties" object in some form, but what form? Here are some initial thoughts from the UN:

> We do not have a settled “standard” way of presenting the sdg data in a geoJSON file.  Roughly we want this to be aligned with SDMX’s data structure definition.  As an example, this is how our global SDG data is not being presented in the UN SDG data hub using the native geoJSON API from ArcGIS. 
> As you can see, in the moment we are presenting the data in a “pivoted” or “wide” format, with one column for each year. 
> I think it would be very good to come up with a common understanding of what this geoJSON format should be, regardless of the platform that produces it (ArcGIS, US/UK platform, etc.)

Here is the example: 
[sdg-example.geo.json.txt](https://github.com/open-sdg/sdg-build/files/2994275/sdg-example.geo.json.txt)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is this fixed by latest updates for v1?

**Comment by brockfanning** [comment]
Yep, closing now.
