### ISSUE TITLE
Test coverage audit/revamp

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-build#181]
A lot of the functionality in this library is not covered by tests. That's one problem; the other problem is that it's not easy for developers (or at least _this_ developer) to add tests. That may be fixable by becoming more familiar with Python test suites in general, but also there may be a way to rewrite the test code to make this easier. So I think we should pick an approach and move forward, either:

1. Rewrite the existing test suite to make it more understandable, and then add full coverage, OR
2. Put in the work to understand the existing test suite, and then add full coverage.

**Comment by jwestw** [comment]
Would it be good to first understand what these tests are doing? As the code doesn't look crazy hard, I think it might be good to unpick it and document it then decide whether to revamp (partly by adding more documentation) or replace.

**Comment by brockfanning** [comment]
@jwestw The things that the tests already cover are:
1. [check_all_csv() function](https://github.com/open-sdg/sdg-build/blob/master/tests/test_check_csv.py): This is a deprecated function that is actually using [open_sdg_check](https://github.com/open-sdg/sdg-build/blob/master/sdg/open_sdg.py#L179) behind the scenes. So this test really covers open_sdg_check(). We'll remove this test at version 2.0.0, when we can drop deprecated stuff, though we'll need to add a test that directly covers open_sdg_check().
2. [check_all_meta() function](https://github.com/open-sdg/sdg-build/blob/master/tests/test_check_meta.py): This is another deprecated function also using open_sdg_check(). We'll remove this test at version 2.0.0.
3. ["edge" detection](https://github.com/open-sdg/sdg-build/blob/master/tests/test_edge_detection.py): This "edge" stuff is still being used and needs to continue to be tested. This is how Open SDG is able to automatically calculate the parent/child relationships of the disaggregations.
4. [path functions](https://github.com/open-sdg/sdg-build/blob/master/tests/test_path.py): This covers a couple of path-related helper functions that are still being used, and so need to continue to be tested.
5. [builds](https://github.com/open-sdg/sdg-build/blob/master/tests/test_build.py): This is the big one where the most important tests are, covering the input/output functionality. It's not covering everything though. Right now it covers:
    * The typical Open SDG input:
        * CSV data
        * YAML/Markdown metadata
        * SDG Translations
        * _prose.yml schema
     * The typical Open SDG output:
       * JSON data and metadata
       * JSON reporting status
       * JSON translations
       * JSON schema
       * GeoJSON
    * Documentation pages, like the disaggregation report

There are several notable things that we are not testing at all:
1. SDMX input of any kind
2. Excel, CSV, or YAML-only metadata input
3. Disaggregation status
4. Zip file exports

In addition, some of the existing tests may be insufficient. For example, the test of the disaggregation report only checks to make sure certain pages exists at all. But it does not test specific things on the pages (like confirming the number of disaggregations listed, etc.)

My main concern --  and the reason for my posting this issue -- is that it's not _obvious_ how to add new tests for these missing things. That may be due to my inexperience with Python testing, but that is the point: I would like to structure the tests so that it's simple for a relative beginner to add a new one, so that we don't end up with so many untested features, like we have now.

**Comment by jwestw** [comment]
Thank you Brock

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @otis-bath This might be something to pursue - we still have a deficit of test coverage on sdg-build.
