### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-build#2]
This will need to be versioned, so let's tag an initial release. @dougmet

**Comment by brockfanning** [comment]
@dougmet Just FYI, I pushed up a 0.1.0 tag.

**Comment by brockfanning** [comment]
Actually I just noticed that there is already a version number in code: https://github.com/open-sdg/sdg-build/blob/master/setup.py
So I also added a tag of 0.2.0. I'm not too familiar with pip and requirements.txt and tag numbers, so I may be doing this wrong. Would this be the correct line for a `requirements.txt` file: `git+git://github.com/open-sdg/sdg-build@0.2.0#egg=sdg` ?

**Comment by dougmet** [comment]
I think the tag in the requirements file will refer to the tag in GitHub. If memory serves the one in `setup.py` doesn't have to match -- even though it absolutely should.
