### ISSUE TITLE
Stats percentages can add up to more than 100%

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-build#26]
In some situations, the percentages for each status in the stats data adds up to more than 100% (probably always 101%, due to rounding?). I'm not sure what the trigger for the bug is, but [here](https://G205SDGs.github.io/sdg-data/stats/reporting.json) is a current example.

**Comment by dougmet** [comment]
It'll be here https://github.com/open-sdg/sdg-build/blob/9e6de13a7f0ba52acfb5c823f672abbc094b5049/sdg/stats.py#L54

So 30.6 + 30.6 + 38.8 would give (31 + 31 + 39 = 101)

What would the desired output be in this case? Decimal? I admit I had assumed if I rounded to 1dp I would get complaints! But it's easily changed.

**Comment by dougmet** [comment]
Probably "put it back how it was" of course. Which was a little fancy: https://github.com/open-sdg/open-sdg/blob/52df833cfce6f6942306c0f5de55a17121fcaf10/_includes/assets/js/reportingStatus.js#L14 but we can do it.

**Comment by brockfanning** [comment]
@dougmet My first thought is to let the output have decimals, because CSS widths will respect decimals in percentages. If people complain about the decimals showing up in the displayed value, maybe we could use the Jekyll filter "round" for the human-readable part? (and not the CSS style part)
