### ISSUE TITLE
No data outputted - SDMX output

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#263]
When I use `constrain_data: true`, no data at all is being output:
https://lucygwilliamadmin.github.io/sdg-sdmx-data/sdmx/all.xml

Looking at the [data for 1.1.1](https://lucygwilliamadmin.github.io/sdg-sdmx-data/en/data/1-1-1.json), the [column mapping](https://github.com/ONSdigital/sdg-sdmx-data/blob/develop/column_mapping.csv), the [code mapping](https://github.com/ONSdigital/sdg-sdmx-data/blob/develop/code_mapping.csv) and the data config, at least 1.1.1 should be showing right?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think the PR #264 should resolve it by changing the point when the hardcoded column renaming happens.
