### ISSUE TITLE
SDMX API Dataflow version is no longer available

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#291]
@brockfanning 
Currently for the UN SDMX API input, we are pointing at v1.3 of the SDG Dataflow:
https://github.com/open-sdg/sdg-build/blob/1.8.0-dev/sdg/inputs/InputSdmxMl_UnitedNationsApi.py#L54

However, that is no longer available:
https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.3

We need to update the version (to 1.7?)

This is also something we need to check and implement each version unless there is a way to point at latest version?

**Comment by LucyGwilliamAdmin** [comment]
I was also getting the same earlier when I was trying to load 1.7 in the browser but I just had a thought - it might be because it's trying to load so much data as there's no further queries so I just tried the following in the browser and seems to work for me:

https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH/...826+827+828+829.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD (all series for UK)

**Comment by brockfanning** [comment]
Ah, good news, that makes sense. So then I think we can just remove the version number like in your example above?

**Comment by LucyGwilliamAdmin** [comment]
Yeah, I think that makes sense
