### ISSUE TITLE
Redesign backend with OO

### ISSUE THREAD

**Issue by dougmet** [open-sdg/sdg-build#4]
Copied through from ONSdigital/sdg-build#9

This package has grown from disconnected scripts into something fairly reusable and testable. However, it's probably time to think about the design pattern of how data is stored on the backend. Here are some core classes that I think we'll want:

indicator: Hold data and metadata for an indicator. It will have write methods
site: Less certain on this. Some combination of the path functions and schema. Perhaps this is a holding class for indicator objects.

Post ideas here. Main requirement is that this is a back-end change and shouldn't break anything for sdg-data.

**Comment by dougmet** [comment]
As noted from #9 need to think about how the internal data model serves sdmx as well as our immediate needs.

**Comment by dougmet** [comment]
An early case of this is being tested with the `Schema` class in #14 . The idea here is that it can load from multiple schema files (only prose for now), store data internally in a consistent manner (a big dictionary for now) and write out to different formats (currently back to prose-style).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is this complete?

(sorry for all the notifications - just going through and seeing which ones can be closed)

**Comment by brockfanning** [comment]
Yes I think we can close this one. There is still more we can do, but we can tackle those in new issues.
