### ISSUE TITLE
site repo build to trigger after data repo build

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#40]
Would it be possible for the site branch to build automatically after the data branch has built?

**Comment by dougmet** [comment]
Hmm. Maybe with some effort. It looks like with the right tokens we could get the data build to kick the site build if it succeeds (I'm guessing master/dev only).

https://docs.travis-ci.com/user/triggering-builds/

A blog post that does something like this is here:
https://iranzo.github.io/blog/2018/12/11/travis-to-trigger-build-in-another-repo/

But it's another layer of complexity.

**Comment by brockfanning** [comment]
In theory it should be possible, but like @dougmet implies it would need to be done at the CI level. And I suspect it would need to be specific to the CI service being used (CircleCI or TravisCI). In other words the code for this wouldn't be in sdg-build, it would probably go in open-sdg-data-starter, as a script and some CircleCI config.

One quirk is that it would need to have a built-in delay, because in my experience, you can't immediately trigger a site build after doing a data build. It takes a few minutes at least for Github Pages to fully register the new build. I'm sure there are Travis/Circle commands for waiting, so it's not a huge challenge, but just something to keep in mind.

**Comment by LucyGwilliamAdmin** [comment]
Also looks like there's this solution for Circle CI:

https://discuss.circleci.com/t/if-a-build-completes-in-one-project-is-there-a-way-to-trigger-build-on-another-project/23941

**Comment by LucyGwilliamAdmin** [comment]
So I've managed to get a build to be triggered (with Circle) but got this error on the resulting build:
![image](https://user-images.githubusercontent.com/43404358/61297629-86eb8c80-a7d4-11e9-9f75-aa440fce4fea.png)

**Comment by LucyGwilliamAdmin** [comment]
@dougmet @brockfanning do you know if this would be something to do with the [circle config file in the site repo](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/.circleci/config.yml)?

**Comment by LucyGwilliamAdmin** [comment]
Maybe because instead of `build` we have `deploy_staging` and `deploy_prod`?

**Comment by LucyGwilliamAdmin** [comment]
I've got passed that error now. I've managed to get the site develop branch to build after the data develop branch has built. 

Just need to figure out how to do it for the master branch now, since the job has a diff name

**Comment by LucyGwilliamAdmin** [comment]
Currently the command looks like this:
curl -u ${CIRCLE_TOKEN}: \
       -d build_parameters[CIRCLE_JOB]=deploy_staging \
       https://circleci.com/api/v1/project/$ORGANIZATION/$PROJECT/tree/$CIRCLE_BRANCH

but I guess instead we'd want something like:
if ORGANIZATION==staging_org:
curl -u ${CIRCLE_TOKEN}: \
       -d build_parameters[CIRCLE_JOB]=deploy_staging \
       https://circleci.com/api/v1/project/$ORGANIZATION/$PROJECT/tree/$CIRCLE_BRANCH
else if ORGANIZATION==prod_org:
curl -u ${CIRCLE_TOKEN}: \
       -d build_parameters[CIRCLE_JOB]=deploy_prod \
       https://circleci.com/api/v1/project/$ORGANIZATION/$PROJECT/tree/$CIRCLE_BRANCH

The issues I'm having with this I'm not sure how if statements work in .yml (but I'm sure I can google to figure that out) and the other is that currently ORGANIZATION is an environment variable stored in the open-sdg-data-starter repo on Circle and currently equals open-sdg-data-starter, not sure how I would go about this changing depending on whether the develop branch is being built or the master branch is being built - I was hoping you might be able to advise on this @dougmet @brockfanning ?

**Comment by LucyGwilliamAdmin** [comment]
Apparently, I was overthinking things since I haven't actually changed anything but a build of the data master branch triggers the build of a site master branch. I guess the only thing is now, is that the build is triggered within the build stage of the data master branch build rather than the deploy_prod stage, meaning the live site starts building before the deploy_prod stage finished on the data side?

@brockfanning is this going to be a problem? Is there where I need to tell it to wait?

(Sorry for all the comments)

**Comment by LucyGwilliamAdmin** [comment]
Nevermind - got it working now

**Comment by LucyGwilliamAdmin** [comment]
I have just made this [pull request](https://github.com/open-sdg/open-sdg-data-starter/pull/16) to make the changes to open-sdg/open-sdg-data-starter

I will add something to the docs as well.

**Comment by LucyGwilliamAdmin** [comment]
Can also use provided API for Travis CI:
https://docs.travis-ci.com/user/triggering-builds/

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning - I've actually got a fix for this for GitHub Actions which Kyrgyzstan are using - this will require change to starter repos and also a small update to docs as one more secret needs to be created. It's pretty straight forward though so will do in next couple of days.

**Comment by LucyGwilliamAdmin** [comment]
Have made required changes: https://github.com/open-sdg/open-sdg-data-starter/pull/29

And also added some instructions to quick start: https://github.com/open-sdg/open-sdg/pull/605

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning think this is in the starter repos right?

**Comment by LucyGwilliamAdmin** [comment]
Closing as in starting repos and docs
