### ISSUE TITLE
Error if SDMX file has more than one series

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#42]
Some SDMX files have more than one series e.g. 1.5.2:
![image](https://user-images.githubusercontent.com/43404358/62708896-32f75080-b9ec-11e9-94fe-f43be4baa60f.png)

which is causing this type of error:
![image](https://user-images.githubusercontent.com/43404358/62708780-f9bee080-b9eb-11e9-8ce2-6bd34376d75b.png)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning what is the purpose of `indicator_id_map`?

Is it to tell the tool what indicator the sdmx file belongs to and so where to put the data on the tool?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin The indicator_id_map parameter is to explicitly make sure that the input knows which Series' belong to which indicators. So, if an SDMX file has more than one series, then you may need more than one entry in the indicator_id_map dict.

Note that the input tries to figure out the indicator id based on the indicator_id_xpath, but if it can't then it will fail without an entry in indicator_id_map. The thing about "Proportion" is evidence of this failure -- it thinks that the indicator id is "Proportion", which is obviously going to cause problems.

If you don't want to have to use the indicator_id_map parameter, another quick fix might be to add the indicator ID at the beginning of the indicator name, in the SDMX DSD. So instead of "Some indicator name", you would put "1.1.1 Some indicator name".

**Comment by LucyGwilliamAdmin** [comment]
Ah ok, great thanks. So does it matter if the same series appears twice? e.g.
{ SERIESCODE1 : 1.1.1, SERIESCODE1: 1.2.1 }

**Comment by brockfanning** [comment]
Ah, hmm, that may actually be a problem. I wonder if lists work. Maybe try:
```
{
  SERIESCODE1: ['1.1.1', '1.2.1']
}
```

**Comment by LucyGwilliamAdmin** [comment]
Actually that might be what is causing #43 :
In this mapping:
https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/blob/sdmx/code_mapping.csv
some of the SERIES are linked to more than one indicator code, where this is the case, I am receiving the error mentioned in #43

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning, so with`'` around the indicator codes?

**Comment by brockfanning** [comment]
Yep, they're strings so they need quotes around them.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning so I've uploaded this [csv](https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/blob/sdmx/code_mapping.csv) to the root of the Kyrgyzstan data repo and I'm trying to use this function in output.py to convert it to a dictionary:
![image](https://user-images.githubusercontent.com/43404358/62715094-b66a6f00-b9f7-11e9-8d1c-f466f6ad82c6.png)
but I seem to be getting [this error](https://circleci.com/gh/sdg-kyrgyzstan/open-sdg-data-starter/1600) from Circle:
![image](https://user-images.githubusercontent.com/43404358/62715161-d8fc8800-b9f7-11e9-89e3-6e738e7db1a2.png)
Although it works fine when I try and do it with Python locally. I think it may be because the rows with commas in have " " added to them when a csv it loaded to GitHub whereas when I look at the df created in python locally there is no " ".

Have you come across this before? Is there a way to remedy it?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'm now getting [this error](https://circleci.com/gh/sdg-kyrgyzstan/open-sdg-data-starter/1614) for 1.5.2:
![image](https://user-images.githubusercontent.com/43404358/62788064-0f043f80-babe-11e9-86c0-75a04f6cab6c.png)

**Comment by LucyGwilliamAdmin** [comment]
I'm pointing to this json file for the mapping:
https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/blob/sdmx/code_mapping.json

**Comment by LucyGwilliamAdmin** [comment]
Actually the other 6 files that were having this problem have now passed the Circle checks. 5.1.2 is the only file remaining with this error but it's different to other six in that it's the only one that is within a list in the mapping.

The files that were also giving this error (but aren't anymore) are 1.a.2, 2.2.2, 5.3.1, 5.5.2, 8.10.1, 9.c.1

**Comment by brockfanning** [comment]
Awesome, thanks for the detail. I think we'll need to make a code change to accommodate this, and I'll look more closely soon.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Would you be able to give this a try with #45 ? I believe you would put this in your requirements.txt: git+git://github.com/brockfanning/sdg-build-1@sdmx-series-for-multiple-indicators

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just tested this and got the same error when trying to upload 1.5.2

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I've pushed a needed tweak to #45, but there are also a couple of issues with `code_mapping.json`:
1. The lists of multiple indicators are in quotes, but should actually just be lists. For example, instead of `"['1-5-1', '11-5-1', '13-1-1']"` it should be `["1-5-1", "11-5-1", "13-1-1"]`.
2. Note that above I used double-quotes around the list items, because JSON requires double-quotes.
Could you fix the code_mapping.json as needed, and try again?

**Comment by LucyGwilliamAdmin** [comment]
I have just edited the file - now in the format e.g.:
`{"SERIES1": "1-1-1",`
 `"SERIES2": ["1-2-1","1-2-2"],`
`...}`
but I'm now getting [this error](https://circleci.com/gh/sdg-kyrgyzstan/open-sdg-data-starter/1648):
![image](https://user-images.githubusercontent.com/43404358/63169777-96f2c800-c02f-11e9-8bfd-ed4dd380bb98.png)

VC_DSR_MISS is the first series in the mapping to have a list as it's value

**Comment by brockfanning** [comment]
That error should be gone with my latest commit to this branch. Are you running this locally or on CircleCI?

If running it locally: Try a `pip install -r scripts/requirements --upgrade`

If running on CircleCI, you may need to "bust the cache" by incrementing the `test-dependencies-v` parameters in the [CircleCI config file](https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/blob/develop/.circleci/config.yml) (eg, changing `test-dependencies-v1` to `test-dependencies-v2`, etc.). [Here's a random example](https://github.com/brockfanning/sdg-data-cambodia/commit/b0ec6b51d8ff61be1c23f514910b1b6d2aae7a4a) of when I need to "bust the cache" on a CircleCI project.

**Comment by LucyGwilliamAdmin** [comment]
I am running on CircleCI - I will try that now

**Comment by LucyGwilliamAdmin** [comment]
No longer getting error - have just approved PR
