### ISSUE TITLE
SDMX: object has no attribute 'indicator'

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#43]
3 files are giving this error when uploaded:
https://circleci.com/gh/sdg-kyrgyzstan/open-sdg-data-starter/1552

**Comment by LucyGwilliamAdmin** [comment]
From #42:
Looks like this error occurs when the same series is mapped to more than one indicator.
Having a list (below) doesn't seem to fix the problem
`{`
  `SERIESCODE1: ['1.1.1', '1.2.1']`
}`

**Comment by brockfanning** [comment]
Ok, I'll work on a fix for #42, then we can see if this is still a problem.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Let me know if this is still happening, now that #42 is fixed.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning yes still happening unfortunately

**Comment by brockfanning** [comment]
I believe this should be fixed now - this pointed out a pretty clear typo. I've fixed it in the master branch.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ok, great - this is working now
