### ISSUE TITLE
Some SDMX data not showing properly

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#58]
So data is showing properly for 1.1.1 on this feature branch I made to test SDMX-ML data upload:
https://sdg.mango-solutions.com/sdmx-files/1-1-1/

But not here on Kyrgyzstan staging site:
https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/1-1-1/

Looks like the data isn't building properly:
https://sdg-kyrgyzstan.github.io/open-sdg-data-starter/data/1-1-1.json

This isn't an issue for all indicator, maybe 4 or 5.

@brockfanning any idea what could be causing this?

**Comment by LucyGwilliamAdmin** [comment]
I've tried to make sdg-kyrgyzstan/open-sdg-site starter have the same things as sdg-indicators but that didn't fix it.

One thing I did notice that is different is that open-sdg-site-starter has `gem "jekyll-get-json", "0.0.1"` in the Gemfile while sdg-indicators doesn't. Is this the wrong version or something? Couldn't see it in use anywhere else and when I removed it I got a Circle error.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Did this get resolved?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning yes, it did - was an issue with the data files.
