### ISSUE TITLE
0.5.0 release

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#73]
Have had quite a few commits since last release so time for a new one?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'm trying to put together some text for a new release but not really sure what features to include. The last minor release is 0.3.0 and the last patch release is 0.3.3 since 0.4.0 and 0.4.1 were added as tags.

**Comment by brockfanning** [comment]
Ok, I'll write something up in the next day.

**Comment by brockfanning** [comment]
PR for changelog updates up at #75

**Comment by brockfanning** [comment]
Closing, just tagged the new release.
