### ISSUE TITLE
Generate reporting statistics

### ISSUE THREAD

**Issue by dougmet** [open-sdg/sdg-build#8]
This supports ONSdigital/sdg-indicators#2851

Alongside individual indicator information we should output statistics across indicators. Propose a whole route of `/stats/`. Starting with `reporting`. For the site we need quite detailed information so that they can build the reporting page.

Initial draft of how it could look is here: https://gist.github.com/dougmet/98a7be9b5c92e0ab0bfe6aee141bf6fa

**Comment by Norric1Admin** [comment]
@dougmet I like this approach - so the indicators marked N/A will be reported through a field such as 'applicable' (e.g. Goal 14) under totals. It is not recorded under the 'status' heading - is this required for N/A to appear as a reporting status category, and for indicators to appear as greyed out in the Goal page?

**Comment by dougmet** [comment]
Oh I see. Well what I had in mind is that non-applicable indicators wouldn't contribute to the reporting stats at all. They could easily be greyed out in the goals page -- although people may want a note as to why it's not applicable so the page itself would remain.

**Comment by Norric1Admin** [comment]
OK - to clarify, what we need is a third status category measuring 'Not applicable', and for this category to apply within the Goal page nullifying these indicators in the same way 'Not started' does. These greyed out indicators would be measured as a proportion of the total indicators too. Is it possible?

**Comment by dougmet** [comment]
yes

**Comment by Norric1Admin** [comment]
:+1:
