### ISSUE TITLE
Allow local translations to be input in CSV

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#86]
@AnnCorp @brockfanning 

Hi both,

While preparing some of the data label translations i.e for disaggregations/breakdowns for Kyrgyzstan site, I've had a thought.

Even though having translations in yaml format may not be super technical, I think it may still be a little too technical for some users.

In most cases, the yaml file structure is quite straightforward:
key: value

However this can become a little complicated when it comes to keys having colons within them e.g.
Non-communicable disease: Diabetes: Неинфекционные заболевания: диабет.
In the yml file this would need to become
"Non-communicable disease: Diabetes": "Неинфекционные заболевания: диабет" so it does get a little more complicated.

Looking at the [yaml translations input code](https://github.com/open-sdg/sdg-build/blob/master/sdg/translations/TranslationInputYaml.py), I don't think it would be that difficult to allow csv translations input.

I'm thinking ahead of second workshop with Kyrgyzstan where part of the training will be adding translations for data labels - I just think editing a CSV file in Excel where the first column is the key and the second column is the value and then uploading the file would be more user friendly than editing a yaml file, where they would have to cautious of colons (:)

What are your thoughts?

**Comment by brockfanning** [comment]
Definitely, seems like a great idea to me!

**Comment by brockfanning** [comment]
This was implemented in #87
