### ISSUE TITLE
Kyrgyzstan national indicator data not building

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#88]
For some reason, Kyrgyzstan's national indicator SDMX data doesn't seem to be building e.g. [6.4.1.2](https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/6-4-1-2/), [7.3.1.2](https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/7-3-1-2/) and others (pretty sure it's all of them).

@brockfanning not sure what's causing this - checks are passing

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Can you try it out the branch for this PR: #89 

I think this is a bug fix which could resolve that problem.

**Comment by brockfanning** [comment]
This was fixed in #89
