### ISSUE TITLE
Import from SDMX API or remote SDMX files

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-build#9]
Many countries will have their data available in an SDMX API or in remote SDMX files. If we could implement an automated import from these sources, that would help countries get their data into Open SDG (or other) platforms.

So this would be an alternative source of data/metadata, as opposed to the normally expected CSV and YAML. I assume that the output of this import would be the same JSON files that this library already creates?

For those on recent calls about this, I mistakenly thought I had done this before, but I was thinking of the "SDG API", which I tried out [here](https://github.com/GSA/sdg-indicators-usa/pull/861). But this would be something very different and would involve SDMX DSDs.

As a next step we can identify an existing SDMX API (or file) and start thinking about how to convert it to our JSON.

**Comment by dougmet** [comment]
Converting to JSON isn't a problem. Really there's an internal data model and it outputs to whatever. So it's all about reading it into the internal model.

Right now the internal model is really close to the open-sdg output formats. It may be that the internal model needs to change to cope with SDMX and we end up building converters to and from that.

In fact if careful thought is applied this could go together with #4 to make a robust internal data format.

**Comment by AnnCorp** [comment]
From: Daniel Eshetie [mailto:eshetie@un.org] 
Dear Brock,
In case of the Cambodia implementation the draft DSD was used in .Stat suite to publish Cambodia’s SDMX Web service end point as follows
 http://cambodgia-statvm1.eastasia.cloudapp.azure.com/SeptemberDisseminateNSIService 

To get the Global SDGs dataset for a selected indicators for Cambodia, use the following query
http://cambodgia-statvm1.eastasia.cloudapp.azure.com/SeptemberDisseminateNSIService/rest/data/UNSD,DF_SDG,1.0/ 
 
To get their localized datasets including subnational areas based on a customized Global DSD, use the following query:
 http://cambodgia-statvm1.eastasia.cloudapp.azure.com/SeptemberDisseminateNSIService/rest/data/KH_NIS,DF_SDG_KH,1.0/
 
By default, the query returns data in the SDMX-ML 2.1 Generic format. You need to set up the Accept HTTP header to application/json to get the data back as SDMX-json using postman as you see below. Abdulla will add any additional point I missed in case.
 
Regards,
Daniel

**Comment by brockfanning** [comment]
A note - we had discussed focusing first on abstracting the internal model, like @dougmet describes above. I've got an attempt at that here: #16 

We should tackle that first (reviews are welcome!) and then come back to this - but in the meantime I'll be working on understanding the SDMX-json output from the example above.

**Comment by brockfanning** [comment]
This has been merged in with #37 so I'll close this.
