### ISSUE TITLE
Input metadata in CSV

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#97]
From slack:
@Brock Fanning quick query if you can help - just wondering how much work it would be to add CSV metadata input? I'm envisaging countries being able to upload a CSV with metadata field in first column and value in second column, and then country would also need to a mapping just to tell site how to map human-readable labels to the internal metadata field keys - do you think this would be a lot of work?

and also whether it would still be possible to use markdown in the values? Or is that unrelated to the file being markdown, and just depend on whether markdownify is used?

@Lucy Gwilliam Not too hard at all, thanks to the way sdg-build is architected. Markdown could still be used in the value cells, yes.

I'm actually looking at the yamlmd input script now and looks pretty straightforward

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning 
so far I've just made a new file here for inputting csv metadata: https://github.com/open-sdg/sdg-build/blob/csv-metadata/sdg/inputs/InputCSVMeta.py

I'm now looking at [meta.py](https://github.com/open-sdg/sdg-build/blob/csv-metadata/sdg/meta.py) - just wondering what type of object the returned `meta` is?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin The returned `meta` is a Python dict, with all the metadata, plus an additional `page_content` key that has whatever was below the `---` in the .md file.

A couple notes:
1. You don't have to reference any external files like meta.py. You can just put all the code in the InputCSVMeta.py file.
2. You don't have to worry about that multilingual subfolder stuff in meta.py. In fact I think we can probably take that stuff out of meta.py.
3. To keep things straightforward, I guess you would have the input expect one of the fields to be called `page_content`?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think I've nearly got it but I'm getting this error:
https://github.com/LucyGwilliamAdmin/sdg-data-quick-start/runs/436845283?check_suite_focus=true

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin On line 30 you're making use of a legacy function "input_path". I think that's returning a .md filename. I'd suggest doing this without using any of the legacy functions, if possible. To start I would try to keep all the code inside the class itself.

**Comment by brockfanning** [comment]
Fixed by #102
